server:
  port: 10002
spring:
  application:
    name: money-management-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/money_management?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 521428Slyt!
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL57Dialect
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.57.9:8848
com:
  gapache:
    security:
      register-remote: true
      update-resources: true
      client-id: money123456money
    job:
      executor:
        name: 金钱管理
        from-server-public-key: fromServerPublicKey
        to-server-private-key: toServerPrivateKey
        local-port: 10000
    app:
      configs:
        sensen:
          name: husen
