#nacos:
#  config:
#    bootstrap:
#      enable: true
#      # 主配置服务器地址
#    server-addr: 118.24.38.46:8848
#    # 主配置 data-id
#    data-ids: user
#    # 主配置 group-id
#    group: DEVELOP
#    # 主配置 配置文件类型
#    type: yaml
#    # 主配置 开启自动刷新
#    auto-refresh: true
#    # 主配置 最大重试次数
#    max-retry: 10
#    # 主配置 重试时间
#    config-retry-time: 2333
#    # 主配置 配置监听长轮询超时时间
#    config-long-poll-timeout: 46000
#    # 主配置 开启注册监听器预加载配置服务（除非特殊业务需求，否则不推荐打开该参数）
#    enable-remote-sync-config: true
server:
  port: 10005
spring:
  application:
    name: user-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.57.9:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/user?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 521428Slyt!
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL57Dialect
com:
  gapache:
    security:
      client-id: user123456user
      register-remote: true
      update-resources: true

