apiVersion: v1
kind: Pod
metadata:
  name: liveness-exec-pod
  namespace: default
spec:
  containers:
    - name: liveness-exec-container
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ['/bin/sh', '-c', 'touch /tmp/live; sleep 60; rm -rf /tmp/live; sleep 3600']
      livenessProbe:
        exec:
          command: ['test', '-e', '/tmp/live']
        initiaDelaySeconds: 1
        periodSeconds: 3
# 检测探针-存活检测
# kubectl get pod
# kubectl describe pod [pod name]
# kubectl exec [pod name] -it -- /bin/sh
