server:
  port: 9972
spring:
  application:
    name: job-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.57.9:8848
        metadata:
          server:
            port: ${com.gapache.job.server.port}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/job_server?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 521428Slyt!
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL57Dialect
  redis:
    host: 127.0.0.1
    port: 6379
  mail:
    username: 1178515826@qq.com
    password: vguweaupstlzjjfc
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
com:
  gapache:
    redisson:
      address: redis://127.0.0.1:6379
      database: 1
    job:
      server:
        port: 9926
        to-executor-private-key: toExecutorPrivateKey
        from-executor-public-key: fromExexutorPublicKey
    security:
      client-id: job123456job
      update-resources: true
      register-remote: true